name: Create Issues from Draft Files
on:
  push:
    paths:
      - ".github/issues_draft/**"

jobs:
  create:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v4
      - name: Create or update issues
        uses: peter-evans/create-issue-from-file@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-folder: .github/issues_draft
