name: Create Issues from Draft Files
on:
  push:
    paths:
      - ".github/issues_draft/**"

jobs:
  create:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v4
      - name: Create issues from folder
        uses: mendelt/pair-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          directory: .github/issues_draft
          glob: "*.md"
          template: |
            title: {{ title }}
            body: {{ content }}
