name: Create Issues from Draft Files
on:
  push:
    paths:
      - ".github/issues_draft/**"

jobs:
  create-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Create one issue per .md file
        uses: gr2m/create-or-update-issue-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          dirname: .github/issues_draft
          title: "{{frontmatter.title}}"
          body: "{{content}}"
          update_existing: "true"
